name: Detailed Notifications to Microsoft 365
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, closed]
 
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Notify on Push
        if: github.event_name == 'push'
        run: |
          curl -H "Content-Type: application/json" -d "{\"text\": \"🔔 행복 커밋이 차곡차곡 쌓인다 : ${GITHUB_REF} by ${GITHUB_ACTOR}. Commit message: '${{ github.event.commits[0].message }}'.\"}" ${{ secrets.M365_WEBHOOK_URL }}
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTOR: ${{ github.actor }}
      - name: Notify on Pull Request
        if: github.event_name == 'pull_request'
        run: |
          curl -H "Content-Type: application/json" -d "{\"text\": \"🔔 행복 커밋 요청: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}. Action: ${{ github.event.action }}, URL: ${{ github.event.pull_request.html_url }}.\"}" ${{ secrets.M365_WEBHOOK_URL }}
